databases:
  - name: MessageMe
    databaseName: messageme
    user: messageme_user

services:
  - type: web
    name: MessageMe
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: MessageMe
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
