databases:
  - name: message-me
    databaseName: MessageMe
    user: MessageMe

services:
  - type: web
    name: message-me
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: message-me
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
